# 5.my-app-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: default
  labels:
    app: my-app
    tier: backend
    version: "1.0"
  annotations:
    description: "This is a sample application pod"
    maintainer: "devops-team"
spec:
  # 重启策略
  restartPolicy: Always
  # 节点选择器
  nodeSelector:
    kubernetes.io/hostname: "hkkck8smaster001"
    # disktype: ssd
  # 配置容忍度
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    # value: "true"
    # effect: "NoSchedule"
    effect: "NoExecute"
    tolerationSeconds: 10 # 10秒后自动驱逐，需要配合 effect: "NoExecute" 使用

  # 容器定义
  containers:
  - name: main-container
    image: nginx
    # 镜像的拉取策略
    imagePullPolicy: IfNotPresent

    # 容器的启动命令
    command: ["nginx"]
    args: ["-g", "daemon off;"]

    # 容器的端口
    ports:
    - name: http
      containerPort: 80 
      protocol: TCP
    - name: https
      containerPort: 443
      protocol: TCP
    
    # 环境变量
    env:
    - name: ENVIRONMENT
      value: "production"
    - name: LOG_LEVEL
      value: "info"

    # 资源限制(QoS)
    resources:
      requests:
        memory: "64Mi"
        cpu: "256m"
      limits:
        memory: "128Mi"
        cpu: "512m"