# 2.headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app-headless-service
  namespace: default
  labels:
    app: nginx
spec:
  type: ClusterIP # 可以省略，默认类型为 ClusterIP
  selector:
    app: nginx # 选择器，用于匹配 Pod 的标签属于这个 Service
  ports:
    - name: http # 端口名称
      protocol: TCP # 协议类型
      port: 90 # 服务端口
      targetPort: 80 # Pod 端口
  clusterIP: None # 设置为 None，表示这是一个 Headless Service
