apiVersion: v1
kind: Namespace
metadata:
  name: example-monitor-namespaces
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-namespaces-acc
  namespace: example-monitor-namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-namespaces
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-namespaces
subjects:
  - kind: ServiceAccount
    name: monitor-namespaces-acc
    namespace: example-monitor-namespaces
roleRef:
  kind: ClusterRole
  name: monitor-namespaces
  apiGroup: rbac.authorization.k8s.io