apiVersion: v1
kind: Pod
metadata:
  name: my-testrole-pod
spec:
  serviceAccountName: test-cluster-role  # 指定自定义 ServiceAccount
  containers:
    - name: container
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.29.3-linuxarm64